version: '3.8'
services:
  node_backend:
    container_name: salary_hero_test
    image: salary-hero_test:1.0.0
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=salary_hero_db
      - PGUSER=witsuta
      - PGPASSWORD=pass1234
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=witsuta
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=salary_hero_db
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
